name: flutter_linkedin_api
version: 1.0.1
description: 'LinkedIn Auth API'
homepage: 'https://github.com/SmarttersStudio/login_with_linkedin_flutter'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  webview_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

